#Artificial Neural Networks (ANN) 

###In this project we are train our first Neural Networks and deep learning (Artificial Neural Networks (ANN) ) model

##In this project we are using Churn_Modelling dataset its a bank dataset ([data download it here](https://www.kaggle.com/aakash50897/churn-modellingcsv))

In [1]:
# Load dataset
from google.colab import files
upload=files.upload() 

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [2]:
!ls

Churn_Modelling.csv  sample_data


In [3]:
!pwd

/content


In [4]:
# Importing Libaries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix

Using TensorFlow backend.


In [5]:
# Import dataset 
data=pd.read_csv('Churn_Modelling.csv')

In [6]:
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [7]:
len(data)

10000

In [8]:
data.corr()

RowNumber  CustomerId  ...  EstimatedSalary    Exited
RowNumber         1.000000    0.004202  ...        -0.005988 -0.016571
CustomerId        0.004202    1.000000  ...         0.015271 -0.006248
CreditScore       0.005840    0.005308  ...        -0.001384 -0.027094
Age               0.000783    0.009497  ...        -0.007201  0.285323
Tenure           -0.006495   -0.014883  ...         0.007784 -0.014001
Balance          -0.009067   -0.012419  ...         0.012797  0.118533
NumOfProducts     0.007246    0.016972  ...         0.014204 -0.047820
HasCrCard         0.000599   -0.014025  ...        -0.009933 -0.007138
IsActiveMember    0.012044    0.001665  ...        -0.011421 -0.156128
EstimatedSalary  -0.005988    0.015271  ...         1.000000  0.012097
Exited           -0.016571   -0.006248  ...         0.012097  1.000000

[11 rows x 11 columns]

In [9]:
X=data.iloc[:,3:13].values
y=data.iloc[:,-1].values

In [10]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [12]:
# Encoding the dataset
label_encoder_X_1=LabelEncoder()
X[:,1]=label_encoder_X_1.fit_transform(X[:,1])

label_encoder_X_2=LabelEncoder()
X[:,2]=label_encoder_X_2.fit_transform(X[:,2])

transformer=ColumnTransformer(transformers=[('Geography' , OneHotEncoder() , [1])], remainder='passthrough')
X=transformer.fit_transform(X.tolist())
X=X.astype('float64') 

In [13]:
# Split the dataset

In [14]:
X_train , X_test , y_train , y_test=train_test_split(X,y , test_size=0.2 , random_state=42)

In [15]:
 print(X_train[0].shape)

(12,)


In [16]:
# Standard the dataset
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [17]:
# Create Model
cls=Sequential()

cls.add(Dense(output_dim=6 , init='uniform', activation='relu', input_dim=12))

cls.add(Dense(output_dim=6 , init='uniform', activation='relu'))

cls.add(Dense(output_dim=1 , init='uniform', activation='sigmoid'))

# Compile the Model
cls.compile(optimizer='adam', loss='binary_crossentropy' , metrics=['accuracy'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=6, kernel_initializer="uniform")`
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [18]:
# Train the model
cls.fit(X_train, y_train , batch_size=20 , epochs=100)
print("The Model has Successfully Trained")

Epoch 1/100
8000/8000 [==============================] - 3s 436us/step - loss: 0.5455 - accuracy: 0.7936
Epoch 2/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.4366 - accuracy: 0.7945
Epoch 3/100
8000/8000 [==============================] - 2s 215us/step - loss: 0.4309 - accuracy: 0.7945
Epoch 4/100
8000/8000 [==============================] - 2s 218us/step - loss: 0.4272 - accuracy: 0.7945
Epoch 5/100
8000/8000 [==============================] - 2s 213us/step - loss: 0.4247 - accuracy: 0.7945
Epoch 6/100
8000/8000 [==============================] - 2s 212us/step - loss: 0.4226 - accuracy: 0.8140
Epoch 7/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.4204 - accuracy: 0.8215
Epoch 8/100
8000/8000 [==============================] - 2s 219us/step - loss: 0.4186 - accuracy: 0.8256
Epoch 9/100
8000/8000 [==============================] - 2s 216us/step - loss: 0.4171 - accuracy: 0.8292
Epoch 10/100
8000/8000 [==============================]

In [19]:
# Prediction
y_pred=cls.predict(X_test)

In [20]:
y_pred=(y_pred>0.5)

In [21]:
# Compare train model 

In [22]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [ True],
       [False],
       [False]])

In [23]:
y_test=(y_test>0.5)
y_test

array([False, False, False, ...,  True,  True,  True])

In [24]:
len(y_pred)

2000

In [25]:
# Confusion matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[1558,  267],
       [  49,  126]])

In [28]:
from sklearn.metrics import accuracy_score
# Confusion matrix
accuracy_score=accuracy_score(y_pred,y_test)


In [29]:
accuracy_score

0.842